source 'https://rubygems.org'
#production gems go here
gem 'nokogiri'
gem 'puppet'
gem 'librarian-puppet'
gem 'wordlist'
gem 'faker'
gem 'forgery'
gem 'redcarpet'
gem 'rqrcode'
gem 'mini_exiftool_vendored'
gem 'rmagick'
gem 'sshkey'
gem 'zipruby'
gem 'zip-zip'
gem 'credy'
gem 'pg'
gem 'cinch'
gem 'nori'
gem 'bcrypt'
gem 'programr', :git => "http://github.com/robertjwhitney/programr.git"
gem 'process_helper'
gem 'ovirt-engine-sdk'
gem 'duplicate'
gem 'smbhash'
gem 'digest-sha3'
gem 'digest-whirlpool'
gem 'digest-siphash'
gem 'scrypt'
gem 'braille', :git => "http://github.com/nicanor/braille.git"
gem 'bases'
gem 'huffman'
gem 'ruby-graphviz'

#development only gems go here
group :test, :development do
  gem 'minitest'
  gem 'rake'
  gem 'rdoc'
  gem 'yard'
end
