grassmarlin.pdf: grassmarlin.tex header.tex
	latex grassmarlin
	pdflatex grassmarlin
	pdflatex grassmarlin

clean:
	rm -fr auto
	rm -f grassmarlin.aux grassmarlin.log grassmarlin.pdf grassmarlin.dvi grassmarlin.out
